// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDXou-qr9wk7nubBfpO6MKefwv0FIFMc8',
    appId: '1:761992975855:web:f7fbea2f2417d2867e921a',
    messagingSenderId: '761992975855',
    projectId: 'fir-crud-ae7ad',
    authDomain: 'fir-crud-ae7ad.firebaseapp.com',
    storageBucket: 'fir-crud-ae7ad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs3g1rlrvxhpEGi6UpO7Q080kXH-O7MCw',
    appId: '1:761992975855:android:71d21ad52dd7604b7e921a',
    messagingSenderId: '761992975855',
    projectId: 'fir-crud-ae7ad',
    storageBucket: 'fir-crud-ae7ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU2B59PFGuHtPXODGFyWFeEI_LJUCkJkY',
    appId: '1:761992975855:ios:206c6dd5590322997e921a',
    messagingSenderId: '761992975855',
    projectId: 'fir-crud-ae7ad',
    storageBucket: 'fir-crud-ae7ad.appspot.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU2B59PFGuHtPXODGFyWFeEI_LJUCkJkY',
    appId: '1:761992975855:ios:9af3ba008040d9fc7e921a',
    messagingSenderId: '761992975855',
    projectId: 'fir-crud-ae7ad',
    storageBucket: 'fir-crud-ae7ad.appspot.com',
    iosBundleId: 'com.example.instagram.RunnerTests',
  );
}
